name: NASA Project CI

on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  build:
    env:
       CI: true
       MONGO_URL: mongodb://localhost/nasa
    strategy:
     matrix: 
        node-version: [20.x, 22.x]
        mongodb-version: ['4.2', '4.4']
    runs-on: ubuntu-latest

    steps: 
        # Checkout the repository
        - uses: actions/checkout@v3

        # Setup Node.js version based on the matrix
        - name: Use Node.js version ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with: 
            node-version: ${{ matrix.node-version }} 

        # Install server-side dependencies
        - name: MongoDB Action
          uses: SusanDoggie/mongodb-action@0.0.1
          with: 
            mongodb-version: ${{ matrix.mongodb-version }}
        - name: Install server dependencies
          run: npm install

        # Install client dependencies
        - name: Install client dependencies
          run: npm install --prefix client
        - run: npm test


        # Build the client (React) app
        - name: Build client
          run: npm run build --prefix client

